### PR TITLE
Modified form, models, views,and forum files

### PR DESCRIPTION
**Pull request by joe-bollinger**

### CODE REVIEW

**Review by brett-buskirk — COMMENTED** [review]
When I try to run the server, I get an error saying I need to install Pillow:
image

Trying to install Pillow failed on my machine. Did you have to install anything to get the code to work as you currently have it?

**Comment by brett-buskirk** [comment]
Using the following commands seems to work on installing Pillow:

`python -m pip install --upgrade pip`
`python -m pip install --upgrade pillow`

However, once the project is up and running, all the previous user credentials don't work. So it looks like you've overwritten the database.

**Comment by joe-bollinger** [comment]
Yes, I had to erase the database in order to get everything on the same
page so to speak with the database.

**Comment by brett-buskirk** [comment]
Cool, so are you ready for this to be merged?

**Comment by joe-bollinger** [comment]
Added group members as superusers their passwords are 'password', john.wick is back with a password of fluffybunny. Pillow will have to be installed to use images. We corrected the post issue and the tags issue last night. Styling still needs work.

**Review by brett-buskirk — APPROVED** [review]
Great work!

**Pull request merged**
